package lostfacility.event;

import java.time.Instant;

/**
 * Common interface for all state change events generated by the game engine.
 */
public interface GameEvent {

    Instant getTimestamp();

    String getDescription();
}
